version: "3.1"

services:
  #application
  customer-manager:
    build: .
    restart: always
    container_name: customer-manager
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: customer-manager-mongo
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/customer-manager-data:/data/db
      - $HOME/data/customer-manager-bkp:/data/bkp
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo

  mongo-init:
    build: ./mongo-init
    depends_on:
      - mongo